#!/usr/bin/env python3
"""Generate synthesizable twiddle lookup functions from pinned PQClean data."""

from __future__ import annotations

import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parents[1]


def extract(path: pathlib.Path, symbol: str) -> list[int]:
    text = path.read_text(encoding="utf-8")
    match = re.search(
        rf"(?:static\s+)?const\s+int(?:16|32)_t\s+{re.escape(symbol)}\s*\[[^]]+\]\s*=\s*\{{(.*?)\}};",
        text,
        re.S,
    )
    if match is None:
        raise RuntimeError(f"could not find {symbol} in {path}")
    return [int(token) for token in re.findall(r"-?\d+", match.group(1))]


def emit_case(name: str, width: int, values: list[int]) -> str:
    lines = [
        f"function automatic signed [{width - 1}:0] {name};",
        "    input [7:0] index;",
        "    begin",
        "        case (index)",
    ]
    for index, value in enumerate(values):
        if value < 0:
            literal = f"-{width}'sd{abs(value)}"
        else:
            literal = f"{width}'sd{value}"
        lines.append(f"            8'd{index}: {name} = {literal};")
    lines.extend(
        [
            f"            default: {name} = {width}'sd0;",
            "        endcase",
            "    end",
            "endfunction",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    mldsa = extract(
        ROOT / "third_party/PQClean/crypto_sign/ml-dsa-65/clean/ntt.c", "zetas"
    )
    mlkem = extract(
        ROOT / "third_party/PQClean/crypto_kem/ml-kem-768/clean/ntt.c",
        "PQCLEAN_MLKEM768_CLEAN_zetas",
    )
    if len(mldsa) != 256 or len(mlkem) != 128:
        raise RuntimeError(f"unexpected table lengths: {len(mldsa)}, {len(mlkem)}")

    output = "\n".join(
        [
            "// SPDX-License-Identifier: Apache-2.0",
            "// Generated by tools/gen_ntt_rom.py from pinned PQClean constants.",
            "// Do not hand edit; regenerate after changing the PQClean pin.",
            "",
            emit_case("mldsa_zeta", 32, mldsa),
            "",
            emit_case("mlkem_zeta", 16, mlkem),
            "",
        ]
    )
    (ROOT / "rtl/lca_ntt_zetas.svh").write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
